# Application layer
symbols:
  - 'BTCUSDT'
  - 'ETHUSDT'
sampling_frequency: 1  # in seconds
downsampling_frequency: 5  # in minutes
resample_frequency: '10S'  # resample frequency
data_points: 10000
api_rate_limit: 10  # max API calls per second
max_workers: 5  # max number of threads

