version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: timescale_db
    networks:
      - app_network
    stdin_open: true
    tty: true
    command: sleep infinity

  db:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timescale_db
    ports:
      - "5432:5432"
    volumes:
      - .timescale_data_dev:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  timescale_data_dev:
